ci: build nearcore manually

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,26 +51,26 @@ jobs:
           cargo build -p mpc-contract --target=wasm32-unknown-unknown --release
           mkdir -p res && cp target/wasm32-unknown-unknown/release/mpc_contract.wasm res/mpc_contract.wasm
 
-      - name: Download near core binary from S3
-        id: download-neard
-        continue-on-error: true
-        run: |
-          os=$(uname)
-          arch=$(uname -m)
-          os_and_arch=${os}-${arch}
-          cd libs/nearcore
+          #- name: Download near core binary from S3
+          #  id: download-neard
+          #  continue-on-error: true
+          #  run: |
+          #    os=$(uname)
+          #    arch=$(uname -m)
+          #    os_and_arch=${os}-${arch}
+          #    cd libs/nearcore
 
-          branch_name=$(git branch -r --contains HEAD | grep -o 'origin/[^ ]*' | sed 's|origin/||' | head -n 1 || echo "no-branch")
-          commit_hash=$(git rev-parse HEAD || echo "no-commit")
+          #    branch_name=$(git branch -r --contains HEAD | grep -o 'origin/[^ ]*' | sed 's|origin/||' | head -n 1 || echo "no-branch")
+          #    commit_hash=$(git rev-parse HEAD || echo "no-commit")
 
-          url="https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${os_and_arch}/${branch_name}/${commit_hash}/neard"
+          #    url="https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${os_and_arch}/${branch_name}/${commit_hash}/neard"
 
-          mkdir -p target/debug
-          curl -o target/debug/neard "${url}" || echo "curl failed with URL: ${url}"
-          chmod +x target/debug/neard
+          #    mkdir -p target/debug
+          #    curl -o target/debug/neard "${url}" || echo "curl failed with URL: ${url}"
+          #    chmod +x target/debug/neard
 
       - name: Build near core as fallback
-        if: steps.download-neard.outcome != 'success'
+          #if: steps.download-neard.outcome != 'success'
         run: |
           cd libs/nearcore
           cargo build -p neard
@@ -93,12 +93,14 @@ jobs:
       - name: Run signature request pytest
         run: |
           source pytest/venv/bin/activate
-          python3 pytest/tests/index_signature_request.py
+          cd pytest
+          python3 tests/index_signature_request.py
 
-      - name: Run update request pytest
+      - name: Run update contract pytest
         run: |
           source pytest/venv/bin/activate
-          python3 pytest/tests/update_test.py
+          cd pytest
+          python3 tests/update_test.py
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
