fix ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,9 +61,12 @@ jobs:
           cd libs/nearcore
 
           branch_name=$(git branch -r --contains HEAD | grep -o 'origin/.*' | sed 's|origin/||' | head -n 1 || echo "no-branch")
-          commit_hash=$(git rev-parse HEAD)
+          commit_hash=$(git rev-parse HEAD || echo "no-commit")
+
+          url="https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${os_and_arch}/${branch_name}/${commit_hash}/neard"
+
           mkdir -p target/debug
-          curl -o target/debug/neard https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${os_and_arch}/${branch_name}/${commit_hash}/neard
+          curl -o target/debug/neard "${url}" || echo "curl failed with URL: ${url}"
           chmod +x target/debug/neard
 
       - name: Build near core as fallback
@@ -84,7 +87,7 @@ jobs:
         run: |
           python3 -m venv pytest/venv
           source pytest/venv/bin/activate
-          pip install -r libs/nearcore/pytest/requirements.txt
+          pip install -r pytest/requirements.txt
 
       - name: Run signature request pytest
         run: |
