mpc contract: remove limits on signature requests & add pytest for updating contract (#136)
* remove limits on signature requests, add pytest for updating contracts
- leaner contract state V1 without soft and hard limits on the number of concurrent request and minimal signature deposit (1 yoctonear)
- fix migrate function in contract
- improve pytest folder and add test for upggrading from V0 to V1
- update k256 crate to the latest audited release
- fix ci (fetching nearcore binary from S3)
- add pytest to ci
- update gitignore

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,10 +60,16 @@ jobs:
           os_and_arch=${os}-${arch}
           cd libs/nearcore
 
-          branch_name=$(git branch -r --contains HEAD | grep -o 'origin/.*' | sed 's|origin/||' | head -n 1 || echo "no-branch")
-          commit_hash=$(git rev-parse HEAD)
+          branch_name=master #$(git branch -r --contains HEAD | grep -o 'origin/[^ ]*' | sed 's|origin/||' | head -n 1 || echo "no-branch")
+          commit_hash=$(git rev-parse HEAD || echo "no-commit")
+
+          url="https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${os_and_arch}/${branch_name}/${commit_hash}/neard"
+
           mkdir -p target/debug
-          curl -o target/debug/neard https://s3.us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${os_and_arch}/${branch_name}/${commit_hash}/neard
+          if ! curl -o target/debug/neard "${url}"; then
+            echo "curl failed with URL: ${url}"
+            exit 1
+          fi
           chmod +x target/debug/neard
 
       - name: Build near core as fallback
@@ -84,12 +90,14 @@ jobs:
         run: |
           python3 -m venv pytest/venv
           source pytest/venv/bin/activate
-          pip install -r libs/nearcore/pytest/requirements.txt
+          cd pytest
+          pip install -r requirements.txt
 
       - name: Run pytest
         run: |
           source pytest/venv/bin/activate
-          python3 pytest/index_signature_request.py
+          cd pytest
+          pytest -s
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
